defaults:
  - _self_

model_dir: ???
model_filename: accessibility_equity_dqn_single_vehicle

episodes: 50
save_decision_replay_video: False
decision_replay_fps: 2
dqn_video_episodes: 1
video_fps: 12

hydra:
  job:
    chdir: False
  output_subdir: null
  run:
    dir: ${model_dir}
