defaults:
  - env: default
  - _self_

dqn:
  decision_mode: "routing"
  output_run_name: null
  max_steps: 10
  eval_episodes: 10
  eval_seed: 42
  save_model: True
  total_timesteps: 20_000
  learning_rate: 1e-4
  buffer_size: 50_000
  learning_starts: 1_000
  batch_size: 32
  gamma: 0.99
  train_freq: 4
  target_update_interval: 1_000
  exploration_fraction: 0.2
  exploration_final_eps: 0.05